import { useEffect, useMemo, useState } from 'react';
import type {
  CollisionRow,
  DatasetIndex,
  DatasetMetadata,
  FilterOptions,
  NycDataFile,
  SampleMetadata,
  Summary,
} from '../types';
import { summarizeDatasetMetadata } from '../utils/aggregations';

type Status = 'idle' | 'loading' | 'ready' | 'error';

export interface UseCollisionDataResult {
  /** Full-NYC summary derived from datasetMetadata. Drives hero KPIs + breakdowns. */
  fullSummary: Summary | null;
  /** Full-NYC dataset metadata (for the Full-dataset report). */
  datasetMetadata: DatasetMetadata | null;
  /** Pre-aggregated slices for every supported filter combination. */
  datasetIndex: DatasetIndex | null;
  /** Filter dropdown values. */
  filterOptions: FilterOptions | null;
  /** Loose-shape alias kept for components that still take `sampleMetadata`. */
  sampleMetadata: SampleMetadata | null;
  /** Rows for the record-level data table (≈10k). */
  rows: CollisionRow[];
  /** True once the file is loaded — main view can render. */
  fullReady: boolean;
  /** True once row preview is loaded — data table can render. */
  rowsReady: boolean;
  status: Status;
  error: Error | null;
}

const DATA_FILE = '/data/nyc_data.json';

/**
 * Single source of truth. Loads `nyc_data.json` once — generated by
 * `build_website_data.ipynb`. Every number on the page comes from this file.
 */
export function useCollisionData(): UseCollisionDataResult {
  const [data, setData] = useState<NycDataFile | null>(null);
  const [status, setStatus] = useState<Status>('idle');
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    let cancelled = false;
    setStatus('loading');
    fetch(DATA_FILE)
      .then((r) => {
        if (!r.ok) throw new Error(`${DATA_FILE}: HTTP ${r.status}`);
        return r.json() as Promise<NycDataFile>;
      })
      .then((d) => {
        if (cancelled) return;
        setData(d);
        setStatus('ready');
      })
      .catch((e) => {
        if (cancelled) return;
        setError(e as Error);
        setStatus('error');
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const fullSummary = useMemo<Summary | null>(
    () => (data ? summarizeDatasetMetadata(data.datasetMetadata) : null),
    [data],
  );

  const sampleMetadata = useMemo<SampleMetadata | null>(() => {
    if (!data || !fullSummary) return null;
    // Kept for components that still expect a `SampleMetadata` (extends Summary
    // with an `options` field). All numbers come from the full-dataset summary.
    return { ...fullSummary, options: data.filterOptions };
  }, [data, fullSummary]);

  return {
    fullSummary,
    datasetMetadata: data?.datasetMetadata ?? null,
    datasetIndex: data?.datasetIndex ?? null,
    filterOptions: data?.filterOptions ?? null,
    sampleMetadata,
    rows: data?.sampleRows ?? [],
    fullReady: fullSummary != null,
    rowsReady: (data?.sampleRows?.length ?? 0) > 0,
    status,
    error,
  };
}
